-- lvim-winnav.mux.kitty: the Kitty backend (its remote-control protocol, `kitty @`).
--
-- Kitty has no EDGE QUERY: the `neighbor:<dir>` match spec exists only for the commands that ACT on a
-- window (`kitty @ focus-window --match neighbor:left` — `kitty @ ls --match neighbor:left` is rejected).
-- So the backend answers "am I at the edge" with UNKNOWN (nil) and lets the move itself decide: kitty exits
-- non-zero with "No matching windows" when there is nothing that way, which IS the answer — no fake query,
-- no guess.
--
-- Remote control must be enabled in kitty.conf (`allow_remote_control yes` + a `listen_on` socket).
-- Nothing is marked: kitty's own mapping tests the focused window's foreground process.
--
---@module "lvim-winnav.mux.kitty"

local config = require("lvim-winnav.config")
local exec = require("lvim-winnav.mux.exec")
local amount = require("lvim-winnav.amount")

local M = {}

M.name = "kitty"

-- direction → kitty's neighbor match word, and its resize axis/sign for `resize-window`.
---@type table<LvimWinNavDir, { neighbor: string, axis: string, sign: integer }>
local DIR = {
    left = { neighbor = "left", axis = "horizontal", sign = -1 },
    down = { neighbor = "bottom", axis = "vertical", sign = 1 },
    up = { neighbor = "top", axis = "vertical", sign = -1 },
    right = { neighbor = "right", axis = "horizontal", sign = 1 },
}

--- The kitty executable (config).
---@return string
local function exe()
    return config.multiplexer.commands.kitty
end

--- The remote-control socket kitty exports into its child processes.
---@return string?
local function socket()
    local s = os.getenv("KITTY_LISTEN_ON")
    return (s and s ~= "") and s or nil
end

--- An argv list for a `kitty @` remote-control command, bound to our socket when there is one.
---@param args string[]
---@return string[]
local function argv(args)
    local a = { exe(), "@" }
    local s = socket()
    if s then
        a[#a + 1] = "--to"
        a[#a + 1] = s
    end
    for _, v in ipairs(args) do
        a[#a + 1] = v
    end
    return a
end

--- Are we running inside kitty (with remote control reachable)?
---@return boolean
function M.detect()
    return socket() ~= nil or (os.getenv("TERM") or ""):find("kitty", 1, true) ~= nil
end

--- Is the kitty binary reachable?
---@return boolean
function M.available()
    return exec.has(exe())
end

--- Kitty cannot be ASKED (see the module header): UNKNOWN, so the move itself answers.
---@return boolean? at_edge
function M.current_pane_at_edge(_)
    return nil
end

--- Kitty's layouts have a "zoom" (the stack layout), which has no neighbours anyway — nothing to block.
---@return boolean
function M.is_zoomed()
    return false
end

--- Focus the kitty window in `dir`.
---@param dir LvimWinNavDir
---@return boolean moved
function M.next_pane(dir)
    local d = DIR[dir]
    if not d then
        return false
    end
    return (exec.run(argv({ "focus-window", "--match", "neighbor:" .. d.neighbor })))
end

--- Move our kitty window's border in `dir` by `cells`.
---@param dir LvimWinNavDir
---@param cells integer
---@return boolean resized
function M.resize_pane(dir, cells)
    local d = DIR[dir]
    if not d then
        return false
    end
    return (
        exec.run(argv({
            "resize-window",
            "--axis",
            d.axis,
            "--increment",
            tostring(d.sign * cells),
        }))
    )
end

--- Kitty has no pane-scoped user variable to mark. No-op.
---@return boolean ok
function M.mark_pane(_)
    return false
end

--- Nothing is marked, so nothing is known.
---@return boolean? marked
function M.pane_marked()
    return nil
end

--- The exact commands the backend runs.
---@return table<string, string>
function M.commands()
    return {
        -- the same command answers "is there a window that way" (its exit code) and performs the move
        select = exec.show(argv({ "focus-window", "--match", "neighbor:" .. DIR.left.neighbor })),
        resize = exec.show(argv({ "resize-window", "--axis", DIR.left.axis, "--increment", "-1" })),
    }
end

--- Kitty's mappings live in kitty.conf; there is no query for them.
---@return boolean bound, boolean marks
function M.has_bindings()
    return false, false
end

--- The ready-to-paste block for `kitty.conf`: the mirror keys, passed through to Neovim when the focused
--- window runs it (kitty's own `kitten pass_keys`-style guard via `neighboring_window` + a process match).
---@return string[] lines
function M.config_block()
    local mux = config.multiplexer
    local step = amount.resolve(config.default_amount, "horizontal")
    local L = {
        "# lvim-winnav — the kitty half of the handoff (generated by :LvimWinNav mux-config)",
        "# Requires remote control:  allow_remote_control yes",
        "#                           listen_on unix:/tmp/kitty",
        "# The same keys move/resize the kitty window, unless it runs Neovim — then the key is passed",
        "# through to it and lvim-winnav decides.",
        "",
    }
    for _, dir in ipairs({ "left", "down", "up", "right" }) do
        L[#L + 1] = ("map ctrl+%s neighboring_window %s"):format(
            mux.keys.move[dir]:gsub("^C%-", ""):lower(),
            DIR[dir].neighbor
        )
    end
    for _, dir in ipairs({ "left", "down", "up", "right" }) do
        L[#L + 1] = ("map ctrl+%s resize_window %s %d"):format(
            mux.keys.resize[dir]:gsub("^C%-", ""):lower(),
            (DIR[dir].axis == "horizontal") and ((dir == "left") and "narrower" or "wider")
                or ((dir == "up") and "shorter" or "taller"),
            step
        )
    end
    return L
end

return M
