-- lvim-winnav.mux.wezterm: the WezTerm backend (its `wezterm cli`).
--
-- Edge detection is a real query: `wezterm cli get-pane-direction <Dir>` prints the pane id in that
-- direction and nothing when there is none — so "am I at the edge" is answered without moving anything.
-- Zoom state comes from `wezterm cli list --format json` (the pane's `is_zoomed`, when the running version
-- reports it; an older one simply never blocks the handoff).
--
-- WezTerm needs no pane MARK: its own keybindings can ask Neovim's process/state, and the multiplexer half
-- of the handoff is generated as `wezterm.action.SendKey` fallthrough — nothing to mark, so `mark_pane` is
-- a no-op here.
--
---@module "lvim-winnav.mux.wezterm"

local config = require("lvim-winnav.config")
local exec = require("lvim-winnav.mux.exec")
local amount = require("lvim-winnav.amount")

local M = {}

M.name = "wezterm"

-- direction → WezTerm's own direction word.
---@type table<LvimWinNavDir, string>
local DIR = { left = "Left", down = "Down", up = "Up", right = "Right" }

--- The wezterm executable (config).
---@return string
local function exe()
    return config.multiplexer.commands.wezterm
end

--- Our pane id, from the environment WezTerm exports.
---@return string?
local function pane()
    local p = os.getenv("WEZTERM_PANE")
    return (p and p ~= "") and p or nil
end

--- Are we running inside WezTerm?
---@return boolean
function M.detect()
    return pane() ~= nil
end

--- Is the wezterm binary reachable?
---@return boolean
function M.available()
    return exec.has(exe())
end

--- No pane in `dir`? (`get-pane-direction` prints nothing at the edge.)
---@param dir LvimWinNavDir
---@return boolean
function M.current_pane_at_edge(dir)
    local d = DIR[dir]
    if not d then
        return true
    end
    local ok, out = exec.run({ exe(), "cli", "get-pane-direction", d })
    return not ok or out == ""
end

--- Is our pane zoomed? (Unknown on a version that does not report it ⇒ false: never block the handoff on a
--- guess.)
---@return boolean
function M.is_zoomed()
    local ok, out = exec.run({ exe(), "cli", "list", "--format", "json" })
    if not ok or out == "" then
        return false
    end
    local decoded, panes = pcall(vim.json.decode, out)
    if not decoded or type(panes) ~= "table" then
        return false
    end
    local id = tonumber(pane())
    for _, p in ipairs(panes) do
        if type(p) == "table" and p.pane_id == id then
            return p.is_zoomed == true
        end
    end
    return false
end

--- Activate the pane in `dir`.
---@param dir LvimWinNavDir
---@return boolean moved
function M.next_pane(dir)
    local d = DIR[dir]
    if not d then
        return false
    end
    return (exec.run({ exe(), "cli", "activate-pane-direction", d }))
end

--- Move our pane's border in `dir` by `cells`.
---@param dir LvimWinNavDir
---@param cells integer
---@return boolean resized
function M.resize_pane(dir, cells)
    local d = DIR[dir]
    if not d then
        return false
    end
    return (exec.run({ exe(), "cli", "adjust-pane-size", "--amount", tostring(cells), d }))
end

--- WezTerm has no pane-scoped user option to mark — its config asks the pane itself. No-op.
---@param _on boolean
---@return boolean ok
function M.mark_pane(_on)
    return false
end

--- Nothing is marked, so nothing is known.
---@return boolean? marked
function M.pane_marked()
    return nil
end

--- The exact commands the backend runs.
---@return table<string, string>
function M.commands()
    return {
        edges = exec.show({ exe(), "cli", "get-pane-direction", DIR.left }),
        select = exec.show({ exe(), "cli", "activate-pane-direction", DIR.left }),
        resize = exec.show({ exe(), "cli", "adjust-pane-size", "--amount", tostring(config.default_amount), DIR.left }),
    }
end

--- WezTerm's bindings live in its own Lua config; there is no way to query them from here.
---@return boolean bound, boolean marks
function M.has_bindings()
    return false, false
end

--- The ready-to-paste block for `~/.wezterm.lua`: the mirror keys, forwarded to Neovim when the pane runs it
--- (WezTerm's own `process_name` test) and acting on the WezTerm pane otherwise.
---@return string[] lines
function M.config_block()
    local mux = config.multiplexer
    local step = amount.resolve(config.default_amount, "horizontal")
    local L = {
        "-- lvim-winnav — the WezTerm half of the handoff (generated by :LvimWinNav mux-config)",
        "-- Add to your ~/.wezterm.lua: the same keys move/resize the WezTerm pane, unless the pane runs",
        "-- Neovim — then the key is sent through to it and lvim-winnav decides.",
        "",
        "local wezterm = require('wezterm')",
        "",
        "local function is_nvim(pane)",
        "    return pane:get_foreground_process_name():find('n?vim$') ~= nil",
        "end",
        "",
        "local function forward(key, mods, action)",
        "    return {",
        "        key = key,",
        "        mods = mods,",
        "        action = wezterm.action_callback(function(win, pane)",
        "            if is_nvim(pane) then",
        "                win:perform_action({ SendKey = { key = key, mods = mods } }, pane)",
        "            else",
        "                win:perform_action(action, pane)",
        "            end",
        "        end),",
        "    }",
        "end",
        "",
        "config.keys = {",
    }
    for _, dir in ipairs({ "left", "down", "up", "right" }) do
        local key = mux.keys.move[dir]:gsub("^C%-", "")
        L[#L + 1] = ("    forward('%s', 'CTRL', wezterm.action.ActivatePaneDirection('%s')),"):format(key, DIR[dir])
    end
    for _, dir in ipairs({ "left", "down", "up", "right" }) do
        local key = mux.keys.resize[dir]:gsub("^C%-", "")
        L[#L + 1] = ("    forward('%s', 'CTRL', wezterm.action.AdjustPaneSize({ '%s', %d })),"):format(
            key,
            DIR[dir],
            step
        )
    end
    L[#L + 1] = "}"
    return L
end

return M
