-- lvim-winnav.mux.zellij: the Zellij backend (`zellij action …`).
--
-- Zellij exposes no QUERY: there is no "is there a pane to my left" and no pane-scoped variable. Its
-- `move-focus` is however edge-safe by design — at the outermost pane it simply does nothing (unlike tmux's
-- select-pane, it never wraps) — so the backend reports "not at the edge" and lets Zellij decide, which
-- yields exactly the behaviour the config asks for without a query. Nothing is marked, and zoom is not
-- reported, so a zoomed pane cannot be detected (documented in health).
--
---@module "lvim-winnav.mux.zellij"

local config = require("lvim-winnav.config")
local exec = require("lvim-winnav.mux.exec")
local amount = require("lvim-winnav.amount")

local M = {}

M.name = "zellij"

-- direction → Zellij's direction word.
---@type table<LvimWinNavDir, string>
local DIR = { left = "left", down = "down", up = "up", right = "right" }

--- The zellij executable (config).
---@return string
local function exe()
    return config.multiplexer.commands.zellij
end

--- Are we running inside a Zellij session?
---@return boolean
function M.detect()
    local z = os.getenv("ZELLIJ")
    return z ~= nil and z ~= ""
end

--- Is the zellij binary reachable?
---@return boolean
function M.available()
    return exec.has(exe())
end

--- Zellij cannot be asked: UNKNOWN. Its `move-focus` is a no-op at the outermost pane (it never wraps), so
--- letting it try is exactly right.
---@return boolean? at_edge
function M.current_pane_at_edge(_)
    return nil
end

--- Zellij does not report a zoom (fullscreen) state to a client.
---@return boolean
function M.is_zoomed()
    return false
end

--- Move the focus to the pane in `dir` (a no-op at the outermost pane — Zellij never wraps).
---@param dir LvimWinNavDir
---@return boolean moved
function M.next_pane(dir)
    local d = DIR[dir]
    if not d then
        return false
    end
    return (exec.run({ exe(), "action", "move-focus", d }))
end

--- Grow our pane toward `dir`. Zellij resizes by its OWN fixed step, so `cells` is applied by REPEATING the
--- action — the configured amount still scales the gesture.
---@param dir LvimWinNavDir
---@param cells integer
---@return boolean resized
function M.resize_pane(dir, cells)
    local d = DIR[dir]
    if not d then
        return false
    end
    local ok = false
    for _ = 1, math.max(1, cells) do
        ok = (exec.run({ exe(), "action", "resize", "increase", d }))
        if not ok then
            break
        end
    end
    return ok
end

--- Zellij has no pane-scoped user option. No-op.
---@return boolean ok
function M.mark_pane(_)
    return false
end

--- Nothing is marked, so nothing is known.
---@return boolean? marked
function M.pane_marked()
    return nil
end

--- The exact commands the backend runs.
---@return table<string, string>
function M.commands()
    return {
        select = exec.show({ exe(), "action", "move-focus", DIR.left }),
        resize = exec.show({ exe(), "action", "resize", "increase", DIR.left }),
    }
end

--- Zellij's keybindings live in its KDL config; there is no query for them.
---@return boolean bound, boolean marks
function M.has_bindings()
    return false, false
end

--- The ready-to-paste KDL block: Zellij binds the keys in a "normal" mode block and only forwards them to
--- the pane's program when it is Neovim (its own `MoveFocusOrTab` is replaced by a pass-through).
---@return string[] lines
function M.config_block()
    local mux = config.multiplexer
    local step = amount.resolve(config.default_amount, "horizontal")
    local L = {
        "// lvim-winnav — the Zellij half of the handoff (generated by :LvimWinNav mux-config)",
        "// Zellij cannot test the pane's process, so the keys are bound in a keybind block that Neovim",
        "// UNBINDS while it runs (see the `zellij` section of the README) — the pane program wins.",
        "",
        "keybinds {",
        '    shared_except "locked" {',
    }
    for _, dir in ipairs({ "left", "down", "up", "right" }) do
        L[#L + 1] = ('        bind "%s" { MoveFocus "%s"; }'):format(mux.keys.move[dir], DIR[dir])
    end
    for _, dir in ipairs({ "left", "down", "up", "right" }) do
        L[#L + 1] = ('        bind "%s" { Resize "Increase %s"; }  // step %d'):format(
            mux.keys.resize[dir],
            DIR[dir],
            step
        )
    end
    L[#L + 1] = "    }"
    L[#L + 1] = "}"
    return L
end

return M
